import datetime
from sqlalchemy.dialects.postgresql import VARCHAR, INTEGER, FLOAT, TIMESTAMP, DATE

# mapping from club elo to fb ref
club_name_mapping = {
    # ENG
    "Southampton": "Southampton",
    "Arsenal": "Arsenal",
    "Liverpool": "Liverpool",
    "Crystal Palace": "Crystal Palace",
    "Ipswich": "Ipswich Town",
    "West Ham": "West Ham",
    "Bournemouth": "Bournemouth",
    "Leicester": "Leicester City",
    "Newcastle": "Newcastle Utd",
    "Everton": "Everton",
    "Fulham": "Fulham",
    "Man City": "Manchester City",
    "Forest": "Nott'ham Forest",
    "Chelsea": "Chelsea",
    "Man United": "Manchester Utd",
    "Aston Villa": "Aston Villa",
    "Wolves": "Wolves",
    "Brentford": "Brentford",
    "Tottenham": "Tottenham",
    "Brighton": "Brighton",
    "Leeds": "Leeds United",
    "Burnley": "Burnley",
    "Sunderland": "Sunderland",
    # ESP
    "Barcelona": "Barcelona",
    "Real Madrid": "Real Madrid",
    "Atletico": "Atlético Madrid",
    "Bilbao": "Athletic Club",
    "Villarreal": "Villarreal",
    "Betis": "Betis",
    "Osasuna": "Osasuna",
    "Celta": "Celta Vigo",
    "Valencia": "Valencia",
    "Sociedad": "Real Sociedad",
    "Rayo Vallecano": "Rayo Vallecano",
    "Alaves": "Alavés",
    "Mallorca": "Mallorca",
    "Sevilla": "Sevilla",
    "Girona": "Girona",
    "Espanyol": "Espanyol",
    "Getafe": "Getafe",
    "Leganes": "Leganés",
    "Las Palmas": "Las Palmas",
    "Valladolid": "Valladolid",
    "Levante": "Levante",
    "Elche": "Elche",
    "Oviedo": "Oviedo",
    ## ITA
    "Inter": "Inter",
    "Atalanta": "Atalanta",
    "Napoli": "Napoli",
    "Roma": "Roma",
    "Juventus": "Juventus",
    "Milan": "Milan",
    "Lazio": "Lazio",
    "Fiorentina": "Fiorentina",
    "Bologna": "Bologna",
    "Torino": "Torino",
    "Genoa": "Genoa",
    "Como": "Como",
    "Udinese": "Udinese",
    "Parma": "Parma",
    "Cagliari": "Cagliari",
    "Verona": "Hellas Verona",
    "Lecce": "Lecce",
    "Empoli": "Empoli",
    "Venezia": "Venezia",
    "Monza": "Monza",
    "Sassuolo": "Sassuolo",
    "Pisa": "Pisa",
    "Cremonese": "Cremonese",
    ## GER
    "Bayern": "Bayern Munich",
    "Leverkusen": "Leverkusen",
    "Dortmund": "Dortmund",
    "Frankfurt": "Eint Frankfurt",
    "Stuttgart": "Stuttgart",
    "RB Leipzig": "RB Leipzig",
    "Mainz": "Mainz 05",
    "Freiburg": "Freiburg",
    "Werder": "Werder Bremen",
    "Wolfsburg": "Wolfsburg",
    "Gladbach": "Gladbach",
    "Augsburg": "Augsburg",
    "Union Berlin": "Union Berlin",
    "Hoffenheim": "Hoffenheim",
    "St Pauli": "St. Pauli",
    "Heidenheim": "Heidenheim",
    "Bochum": "Bochum",
    "Holstein": "Holstein Kiel",
    "Koeln": "Köln",
    "Hamburg": "Hamburger SV",
    ## FRA
    "Paris SG": "Paris S-G",
    "Lille": "Lille",
    "Monaco": "Monaco",
    "Marseille": "Marseille",
    "Lyon": "Lyon",
    "Nice": "Nice",
    "Strasbourg": "Strasbourg",
    "Lens": "Lens",
    "Brest": "Brest",
    "Rennes": "Rennes",
    "Toulouse": "Toulouse",
    "Auxerre": "Auxerre",
    "Reims": "Reims",
    "Nantes": "Nantes",
    "Le Havre": "Le Havre",
    "Angers": "Angers",
    "Saint-Etienne": "Saint-Étienne",
    "Montpellier": "Montpellier",
    "Lorient": "Lorient",
    "Paris FC": "Paris FC",
    "Metz": "Metz",
    ## UCL
    "Feyenoord": "Feyenoord",
    "Salzburg": "RB Salzburg",
    "Benfica": "Benfica",
    "Crvena Zvezda": "Red Star",
    "Celtic": "Celtic",
    "PSV": "PSV Eindhoven",
    "Brugge": "Club Brugge",
    "Sporting": "Sporting CP",
    "Dinamo Zagreb": "Dinamo Zagreb",
    "Young Boys": "Young Boys",
    "Shakhtar": "Shakhtar",
    "Sparta Praha": "Sparta Prague",
    "Sturm Graz": "Sturm Graz",
    ## UEL
    "FK Riga": "FK Rīgas FS",
    "Fenerbahce": "Fenerbahçe",
    "Bodoe Glimt": "Bodø/Glimt",
    "PAOK": "PAOK",
    "Braga": "Braga",
    "Alkmaar": "AZ Alkmaar",
    "Elfsborg": "Elfsborg",
    "Porto": "Porto",
    "Twente": "Twente",
    "Midtjylland": "Midtjylland",
    "Hoffenheim": "Hoffenheim",
    "Ajax": "Ajax",
    "M Tel Aviv": "Maccabi Tel Aviv",
    "Anderlecht": "Anderlecht",
    "Dynamo Kyiv": "Dynamo Kyiv",
    "Karabakh Agdam": "Qarabağ",
    "Malmoe": "Malmö",
    "Viktoria Plzen": "Viktoria Plzeň",
    "Rangers": "Rangers",
    "Ferencvaros": "Ferencváros",
    "Besiktas": "Beşiktaş",
    "Slavia Praha": "Slavia Prague",
    "Olympiakos": "Olympiacos",
    "Steaua": "FCSB",
    "Galatasaray": "Galatasaray",
    "St Gillis": "Union SG",
    "Razgrad": "Ludogorets",
    # UECL
    "FK Astana": "Astana FK",
    "HJK Helsinki": "HJK",
    "StGallen": "St. Gallen",
    "Rapid Wien": "Rapid Wien",
    "Backa Topola": "TSC",
    "Mlada Boleslav": "Mladá Boleslav",
    "LASK": "LASK",
    "Noah": "FC Noah",
    "Bueyueksehir": "Başakşehir",
    "The New Saints": "The New Saints",
    "Omonia": "AC Omonia",
    "APOEL": "APOEL",
    "Olimpija Ljubljana": "Olimpija",
    "Legia": "Legia Warsaw",
    "Larne": "Larne FC",
    "Paphos": "Pafos FC",
    "Lugano": "Lugano",
    "Shamrock": "Shamrock Rov",
    "Dinamo Minsk": "Dinamo Minsk",
    "Hearts": "Hearts",
    "Cercle Brugge": "Cercle Brugge",
    "Molde": "Molde",
    "Gent": "Gent",
    "Djurgarden": "Djurgården",
    "Petrocub": "Petrocub",
    "Celje": "NK Celje",
    "FC Kobenhavn": "FC Copenhagen",
    "Panathinaikos": "Panathinaikos",
    "Jagiellonia": "Jagiellonia",
    "Borac Banja Luka": "Borac Banja Luka",
    "Guimaraes": "Vitória",
    "Vikingur": "KV",
}

# Database
db_table_definitions = {
    "elo_table": {
        "name": "current_elos",
        "dtype": {
            "club": VARCHAR(100),
            "country": VARCHAR(100),
            "level": INTEGER(),
            "elo": FLOAT(),
            "updated_at": TIMESTAMP(),
        },
    },
    "fixtures_table": {
        "name": "fixtures",
        "dtype": {
            "home": VARCHAR(100),
            "away": VARCHAR(100),
            "home_goals": INTEGER(),
            "away_goals": INTEGER(),
            "played": VARCHAR(10),
            "neutral": VARCHAR(10),
            "country": VARCHAR(100),
            "date": DATE(),
            "round": VARCHAR(100),
            "notes": VARCHAR(255),
            "updated_at": TIMESTAMP(),
        },
    },
    "domestic_sim_output_table": {
        "name": "sim_standings_dom",
        "dtype": {
            "team": VARCHAR(100),
            "1": FLOAT(),
            "2": FLOAT(),
            "3": FLOAT(),
            "4": FLOAT(),
            "5": FLOAT(),
            "6": FLOAT(),
            "7": FLOAT(),
            "8": FLOAT(),
            "9": FLOAT(),
            "10": FLOAT(),
            "11": FLOAT(),
            "12": FLOAT(),
            "13": FLOAT(),
            "14": FLOAT(),
            "15": FLOAT(),
            "16": FLOAT(),
            "17": FLOAT(),
            "18": FLOAT(),
            "19": FLOAT(),
            "20": FLOAT(),
            "champion": FLOAT(),
            "top_4": FLOAT(),
            "relegation_direct": FLOAT(),
            "relegation_playoff": FLOAT(),
            "league": VARCHAR(100),
            "updated_at": TIMESTAMP(),
        },
    },
    "continental_sim_output_table": {
        "name": "sim_standings_con",
        "dtype": {
            "team": VARCHAR(100),
            "1": FLOAT(),
            "2": FLOAT(),
            "3": FLOAT(),
            "4": FLOAT(),
            "5": FLOAT(),
            "6": FLOAT(),
            "7": FLOAT(),
            "8": FLOAT(),
            "9": FLOAT(),
            "10": FLOAT(),
            "11": FLOAT(),
            "12": FLOAT(),
            "13": FLOAT(),
            "14": FLOAT(),
            "15": FLOAT(),
            "16": FLOAT(),
            "17": FLOAT(),
            "18": FLOAT(),
            "19": FLOAT(),
            "20": FLOAT(),
            "21": FLOAT(),
            "22": FLOAT(),
            "23": FLOAT(),
            "24": FLOAT(),
            "25": FLOAT(),
            "26": FLOAT(),
            "27": FLOAT(),
            "28": FLOAT(),
            "29": FLOAT(),
            "30": FLOAT(),
            "31": FLOAT(),
            "32": FLOAT(),
            "33": FLOAT(),
            "34": FLOAT(),
            "35": FLOAT(),
            "36": FLOAT(),
            "playoff": FLOAT(),
            "direct_to_round_of_16": FLOAT(),
            "po_r32": FLOAT(),
            "po_r16": FLOAT(),
            "po_r8": FLOAT(),
            "po_r4": FLOAT(),
            "po_r2": FLOAT(),
            "po_champion": FLOAT(),
            "league": VARCHAR(100),
            "updated_at": TIMESTAMP(),
        },
    },
}

# Data scraping
elo_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime("%Y-%m-%d")
elo_date = "2025-06-01"  # For testing purposes, set a fixed date
elo_rating_url = f"http://api.clubelo.com/{elo_date}"
fixtures_config = {
    "ENG": {
        "fixtures_url": "https://fbref.com/en/comps/9/2025-2026/schedule/2025-2026-Premier-League-Scores-and-Fixtures",
        "table_id": ["sched_2025-2026_9_1"],
    },
    "ESP": {
        "fixtures_url": "https://fbref.com/en/comps/12/2025-2026/schedule/2025-2026-La-Liga-Scores-and-Fixtures",
        "table_id": ["sched_2025-2026_12_1"],
    },
    "ITA": {
        "fixtures_url": "https://fbref.com/en/comps/11/2025-2026/schedule/2025-2026-Serie-A-Scores-and-Fixtures",
        "table_id": ["sched_2025-2026_11_1"],
    },
    "GER": {
        "fixtures_url": "https://fbref.com/en/comps/20/2025-2026/schedule/2025-2026-Bundesliga-Scores-and-Fixtures",
        "table_id": ["sched_2025-2026_20_1"],
    },
    "FRA": {
        "fixtures_url": "https://fbref.com/en/comps/13/2025-2026/schedule/2025-2026-Ligue-1-Scores-and-Fixtures",
        "table_id": ["sched_2025-2026_13_1"],
    },
    "UCL": {
        "fixtures_url": "https://fbref.com/en/comps/8/2024-2025/schedule/2024-2025-Champions-League-Scores-and-Fixtures",
        "table_id": ["sched_2024-2025_8_2", "sched_2024-2025_8_3"],
    },
    "UEL": {
        "fixtures_url": "https://fbref.com/en/comps/19/2024-2025/schedule/2024-2025-Europa-League-Scores-and-Fixtures",
        "table_id": ["sched_2024-2025_19_2", "sched_2024-2025_19_3"],
    },
    "UECL": {
        "fixtures_url": "https://fbref.com/en/comps/882/2024-2025/schedule/2024-2025-Conference-League-Scores-and-Fixtures",
        "table_id": ["sched_2024-2025_882_2", "sched_2024-2025_882_3"],
    },
}

## Simulation
number_of_simulations = 10000
home_advantage = 80
# leagues_to_sim = list(fixtures_config.keys())
leagues_to_sim = ["ENG", "ESP", "GER", "ITA", "FRA"]
played_cutoff_date = None
schedule_cutoff_date = None

league_rules = {
    "ENG": {
        "has_knockout": False,
        "classification": [
            "points",
            "goal_difference",
            "goals_for",
            "h2h_points",
            "h2h_away_goals_for",
        ],
        "qualification": {
            "champion": [1],
            "top_4": [1, 2, 3, 4],
            "relegation_direct": [18, 19, 20],
        },
    },
    "ESP": {
        "has_knockout": False,
        "classification": [
            "points",
            "h2h_points",
            "h2h_goal_difference",
            "goal_difference",
            "goals_for",
        ],
        "qualification": {
            "champion": [1],
            "top_4": [1, 2, 3, 4],
            "relegation_direct": [18, 19, 20],
        },
    },
    "ITA": {
        "has_knockout": False,
        "classification": [
            "points",
            "playoff",
            "h2h_points",
            "h2h_goal_difference",
            "goal_difference",
            "goals_for",
        ],
        "qualification": {
            "champion": [1],
            "top_4": [1, 2, 3, 4],
            "relegation_direct": [18, 19, 20],
        },
    },
    "GER": {
        "has_knockout": False,
        "classification": [
            "points",
            "goal_difference",
            "goals_for",
            "h2h_points",
            "h2h_goal_difference",
            "h2h_away_goals_for",
            "away_goals_for",
        ],
        "qualification": {
            "champion": [1],
            "top_4": [1, 2, 3, 4],
            "relegation_playoff": [16],
            "relegation_direct": [17, 18],
        },
    },
    "FRA": {
        "has_knockout": False,
        "classification": [
            "points",
            "goal_difference",
            "h2h_points",
            "h2h_goal_difference",
            "h2h_goals_for",
            "h2h_away_goals_for",
            "goals_for",
            "away_goals_for",
        ],
        "qualification": {
            "champion": [1],
            "top_4": [1, 2, 3, 4],
            "relegation_playoff": [16],
            "relegation_direct": [17, 18],
        },
    },
    "UCL": {
        "has_knockout": True,
        "classification": [
            "points",
            "goal_difference",
            "goals_for",
            "away_goals_for",
        ],
        # No relegation info for UCL, exclude or set None
        "qualification": {
            "direct_to_round_of_16": list(range(1, 9)),
            "playoff": list(range(9, 25)),
        },
        "knockout_bracket": [
            (1, "Bye"),
            (16, 17),
            (8, "Bye"),
            (9, 24),
            (4, "Bye"),
            (13, 20),
            (5, "Bye"),
            (12, 21),
            (2, "Bye"),
            (15, 18),
            (7, "Bye"),
            (10, 23),
            (3, "Bye"),
            (14, 19),
            (6, "Bye"),
            (11, 22),
        ],
        "knockout_format": {
            "po_r32": "two-legged",
            "po_r16": "two-legged",
            "po_r8": "two-legged",
            "po_r4": "two-legged",
            "po_r2": "single_game_neutral",
        },
        "knockout_draw": [  # None
            ("Liverpool", "Bye"),
            ("Paris S-G", "Brest"),
            ("Aston Villa", "Bye"),
            ("Atalanta", "Club Brugge"),
            ("Arsenal", "Bye"),
            ("PSV Eindhoven", "Juventus"),
            ("Atlético Madrid", "Bye"),
            ("Real Madrid", "Manchester City"),
            ("Barcelona", "Bye"),
            ("Benfica", "Monaco"),
            ("Lille", "Bye"),
            ("Dortmund", "Sporting CP"),
            ("Inter", "Bye"),
            ("Milan", "Feyenoord"),
            ("Leverkusen", "Bye"),
            ("Bayern Munich", "Celtic"),
        ],
    },
    "UEL": {
        "has_knockout": True,
        "classification": [
            "points",
            "goal_difference",
            "goals_for",
            "away_goals_for",
        ],
        # No relegation info for UCL, exclude or set None
        "qualification": {
            "direct_to_round_of_16": list(range(1, 17)),
            "playoff": list(range(17, 25)),
        },
        "knockout_bracket": [
            (1, "Bye"),
            (16, 17),
            (8, "Bye"),
            (9, 24),
            (4, "Bye"),
            (13, 20),
            (5, "Bye"),
            (12, 21),
            (2, "Bye"),
            (15, 18),
            (7, "Bye"),
            (10, 23),
            (3, "Bye"),
            (14, 19),
            (6, "Bye"),
            (11, 22),
        ],
        "knockout_format": {
            "po_r32": "two-legged",
            "po_r16": "two-legged",
            "po_r8": "two-legged",
            "po_r4": "two-legged",
            "po_r2": "single_game_neutral",
        },
        "knockout_draw": [  # None
            ("Tottenham", "Bye"),
            ("Galatasaray", "AZ Alkmaar"),
            ("Eint Frankfurt", "Bye"),
            ("Ajax", "Union SG"),
            ("Olympiacos", "Bye"),
            ("Twente", "Bodø/Glimt"),
            ("Lazio", "Bye"),
            ("Viktoria Plzeň", "Ferencváros"),
            ("Rangers", "Bye"),
            ("Anderlecht", "Fenerbahçe"),
            ("Athletic Club", "Bye"),
            ("Roma", "Porto"),
            ("Lyon", "Bye"),
            ("FCSB", "PAOK"),
            ("Manchester Utd", "Bye"),
            ("Real Sociedad", "Midtjylland"),
        ],
    },
    "UECL": {
        "has_knockout": True,
        "classification": [
            "points",
            "goal_difference",
            "goals_for",
            "away_goals_for",
        ],
        # No relegation info for UCL, exclude or set None
        "qualification": {
            "direct_to_round_of_16": list(range(1, 17)),
            "playoff": list(range(17, 25)),
        },
        "knockout_bracket": [
            (1, "Bye"),
            (16, 17),
            (8, "Bye"),
            (9, 24),
            (4, "Bye"),
            (13, 20),
            (5, "Bye"),
            (12, 21),
            (2, "Bye"),
            (15, 18),
            (7, "Bye"),
            (10, 23),
            (3, "Bye"),
            (14, 19),
            (6, "Bye"),
            (11, 22),
        ],
        "knockout_format": {
            "po_r32": "two-legged",
            "po_r16": "two-legged",
            "po_r8": "two-legged",
            "po_r4": "two-legged",
            "po_r2": "single_game_neutral",
        },
        "knockout_draw": [  # None
            ("Vitória", "Bye"),
            ("Betis", "Gent"),
            ("Cercle Brugge", "Bye"),
            ("TSC Bačka Top", "Jagiellonia"),
            ("Lugano", "Bye"),
            ("NK Celje", "APOEL"),
            ("Fiorentina", "Bye"),
            ("Panathinaikos", "Manchester City"),
            ("Djurgården", "Bye"),
            ("Pafos FC", "AC Omonia"),
            ("Rapid Wien", "Bye"),
            ("Borac Banja Luka", "Olimpija"),
            ("Legia Warsaw", "Bye"),
            ("Molde", "Shamrock Rov"),
            ("Chelsea", "Bye"),
            ("FC Copenhagen", "Heidenheim"),
        ],
    },
}
